databases:
  - name: docs_first_approach_production
    ipAllowList: []
    user: admin
    plan: free

services:
  - type: web
    name: Docs-first-approach
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docs_first_approach_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
