databases:
  - name: postgres
    ipAllowList: []
    databaseName: docs_first_approach_production
    user: admin

services:
  - type: web
    name: Docs-first-approach
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: docs_first_approach_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
