openapi: 3.1.0

info:
  title: Docs first approach
  version: 1.0.0

tags:
  - name: Books
    description: A library of Books

paths:
  '/api/v1/books':
    get:
      summary: Get a list of books
      operationId: getBooks
      tags: [ Books ]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      summary: Create a book
      operationId: createBook
      tags: [ Books ]
      requestBody:
        description: Book details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
            examples:
              Jessica:
                value:
                  author: Jessica
                  title: Book 2
                  publication_year: 1999
              Ron:
                value:
                  author: Ron
                  title: Book 3
                  publication_year: 2003
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        "422":
          description: Validation failed
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Book:
      type: object
      required: [title, author, publication_year]
      properties:
        title:
          type: string
        author:
          type: string
        publication_year:
          type: integer
